language: cpp
compiler:
 - gcc
 - clang-3.6
os:
 - linux
 - osx
install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" && "$CXX" == "g++" ]]; then brew install gcc5; fi
 - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
   - llvm-toolchain-precise-3.6
  packages:
   - g++-5
   - clang-3.6
notifications:
 email: false
