language: cpp
compiler:
 - gcc
 - clang
os:
 - linux
 - osx
install:
 - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - g++-4.8
notifications:
 email: false
